# Q3. Singular Value Decomposition (SVD):

In [5]:
import numpy as np
np.random.seed(55)
A = np.random.randint(0, 10, size=(5, 5))

In [6]:
U,Sigma,V_transpose = np.linalg.svd(A)
Sigma_mat = np.zeros_like(A, dtype=float)
Sigma_mat[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(Sigma)
print("Matrix U:")
print(U)
print("\nMatrix Sigma:")
print(Sigma_mat)
print("\nMatrix V:")
print(V_transpose.T)

Matrix U:
[[-0.5239559   0.29784396 -0.47058638 -0.56149959  0.31626866]
 [-0.35453368 -0.38207014  0.4237704  -0.5226714  -0.52493955]
 [-0.4517675   0.68920295  0.42259848  0.32959478 -0.18352992]
 [-0.35806032 -0.21104302 -0.60413615  0.43343748 -0.52383691]
 [-0.51717988 -0.49575349  0.23536599  0.33916375  0.56242711]]

Matrix Sigma:
[[26.46973072  0.          0.          0.          0.        ]
 [ 0.          8.73105475  0.          0.          0.        ]
 [ 0.          0.          6.52282787  0.          0.        ]
 [ 0.          0.          0.          3.27526987  0.        ]
 [ 0.          0.          0.          0.          0.920523  ]]

Matrix V:
[[-0.33154694  0.61829594 -0.22830395 -0.15465257 -0.65707431]
 [-0.50678559 -0.53416172 -0.48222877 -0.47356647  0.03209103]
 [-0.18430928  0.56525067 -0.03678458 -0.35402398  0.72099631]
 [-0.54921322  0.03662661 -0.21626038  0.78040118  0.20304872]
 [-0.54556386 -0.10738509  0.81682989 -0.13213025 -0.07847962]]


In [7]:
A_reconstructed = np.dot(U, np.dot(Sigma_mat, V_transpose))
print("Verification that A equals the product of U, Sigma, and V:")
print(np.allclose(A, A_reconstructed))

Verification that A equals the product of U, Sigma, and V:
True
